const guest_table = [
{
guest_id:"aswed178",
name:"????",
email:"chitaka0506@gmail.com",
password:"fionashome301",
ReceptionOnly: false,
SangeetReceptionOnly: false,
SanMuhRec: false,
AllEvents: false,
AllUSJapan: false,
isAttendingMehendi: "no",
mehendiPartySize: 0,
isAttendingHaldi: "no",
haldiPartySize: 0,
isAttendingSangeet: "no",
sangeetPartySize: 0,
isAttendingMuhurtham: "no",
muhurthamPartySize: 0,
isAttendingReception: "no",
receptionPartySize: 0,
isAttendingShinzenshiki: "no",
shinzenshikiPartySize: 0,
isAttendingHiroen: "no",
hiroenPartySize: 0,
lastRSVPUpdateTime: "2024-05-26 10:00",
partyMembers:"avani",
allergies:"none"
},
{
guest_id:"aswed179",
name:"?????????",
email:"sizuki822@kdn.biglobe.ne.jp",
password:"fionashome301",
ReceptionOnly: false,
SangeetReceptionOnly: false,
SanMuhRec: false,
AllEvents: false,
AllUSJapan: false,
isAttendingMehendi: "no",
mehendiPartySize: 0,
isAttendingHaldi: "no",
haldiPartySize: 0,
isAttendingSangeet: "no",
sangeetPartySize: 0,
isAttendingMuhurtham: "no",
muhurthamPartySize: 0,
isAttendingReception: "no",
receptionPartySize: 0,
isAttendingShinzenshiki: "no",
shinzenshikiPartySize: 0,
isAttendingHiroen: "no",
hiroenPartySize: 0,
lastRSVPUpdateTime: "2024-05-26 10:00",
partyMembers:"avani",
allergies:"none"
},
{
guest_id:"aswed180",
name:"Yuka Kitagami / ?????",
email:"Yuka.kitagami@randstad.co.jp",
password:"fionashome301",
ReceptionOnly: false,
SangeetReceptionOnly: false,
SanMuhRec: false,
AllEvents: false,
AllUSJapan: false,
isAttendingMehendi: "no",
mehendiPartySize: 0,
isAttendingHaldi: "no",
haldiPartySize: 0,
isAttendingSangeet: "no",
sangeetPartySize: 0,
isAttendingMuhurtham: "no",
muhurthamPartySize: 0,
isAttendingReception: "no",
receptionPartySize: 0,
isAttendingShinzenshiki: "no",
shinzenshikiPartySize: 0,
isAttendingHiroen: "no",
hiroenPartySize: 0,
lastRSVPUpdateTime: "2024-05-26 10:00",
partyMembers:"avani",
allergies:"none"
},
{
guest_id:"aswed181",
name:"????",
email:"yui-smile-2525@i.softbank.jp",
password:"fionashome301",
ReceptionOnly: false,
SangeetReceptionOnly: false,
SanMuhRec: false,
AllEvents: false,
AllUSJapan: false,
isAttendingMehendi: "no",
mehendiPartySize: 0,
isAttendingHaldi: "no",
haldiPartySize: 0,
isAttendingSangeet: "no",
sangeetPartySize: 0,
isAttendingMuhurtham: "no",
muhurthamPartySize: 0,
isAttendingReception: "no",
receptionPartySize: 0,
isAttendingShinzenshiki: "no",
shinzenshikiPartySize: 0,
isAttendingHiroen: "no",
hiroenPartySize: 0,
lastRSVPUpdateTime: "2024-05-26 10:00",
partyMembers:"avani",
allergies:"none"
},
{
guest_id:"aswed182",
name:"????",
email:"kisetsu0800@docomo.ne.jp",
password:"fionashome301",
ReceptionOnly: false,
SangeetReceptionOnly: false,
SanMuhRec: false,
AllEvents: false,
AllUSJapan: false,
isAttendingMehendi: "no",
mehendiPartySize: 0,
isAttendingHaldi: "no",
haldiPartySize: 0,
isAttendingSangeet: "no",
sangeetPartySize: 0,
isAttendingMuhurtham: "no",
muhurthamPartySize: 0,
isAttendingReception: "no",
receptionPartySize: 0,
isAttendingShinzenshiki: "no",
shinzenshikiPartySize: 0,
isAttendingHiroen: "no",
hiroenPartySize: 0,
lastRSVPUpdateTime: "2024-05-26 10:00",
partyMembers:"avani",
allergies:"none"
},
{
guest_id:"aswed183",
name:"?? ???",
email:"gentaropittsburgh@gmail.com",
password:"fionashome301",
ReceptionOnly: false,
SangeetReceptionOnly: false,
SanMuhRec: false,
AllEvents: false,
AllUSJapan: false,
isAttendingMehendi: "no",
mehendiPartySize: 0,
isAttendingHaldi: "no",
haldiPartySize: 0,
isAttendingSangeet: "no",
sangeetPartySize: 0,
isAttendingMuhurtham: "no",
muhurthamPartySize: 0,
isAttendingReception: "no",
receptionPartySize: 0,
isAttendingShinzenshiki: "no",
shinzenshikiPartySize: 0,
isAttendingHiroen: "no",
hiroenPartySize: 0,
lastRSVPUpdateTime: "2024-05-26 10:00",
partyMembers:"avani",
allergies:"none"
},
{
guest_id:"aswed184",
name:"?? ??",
email:"kyz461228@gmail.com",
password:"fionashome301",
ReceptionOnly: false,
SangeetReceptionOnly: false,
SanMuhRec: false,
AllEvents: false,
AllUSJapan: false,
isAttendingMehendi: "no",
mehendiPartySize: 0,
isAttendingHaldi: "no",
haldiPartySize: 0,
isAttendingSangeet: "no",
sangeetPartySize: 0,
isAttendingMuhurtham: "no",
muhurthamPartySize: 0,
isAttendingReception: "no",
receptionPartySize: 0,
isAttendingShinzenshiki: "no",
shinzenshikiPartySize: 0,
isAttendingHiroen: "no",
hiroenPartySize: 0,
lastRSVPUpdateTime: "2024-05-26 10:00",
partyMembers:"avani",
allergies:"none"
},
{
guest_id:"aswed185",
name:"????????????",
email:"taiki.okabe1188@gmail.com",
password:"fionashome301",
ReceptionOnly: false,
SangeetReceptionOnly: false,
SanMuhRec: false,
AllEvents: false,
AllUSJapan: false,
isAttendingMehendi: "no",
mehendiPartySize: 0,
isAttendingHaldi: "no",
haldiPartySize: 0,
isAttendingSangeet: "no",
sangeetPartySize: 0,
isAttendingMuhurtham: "no",
muhurthamPartySize: 0,
isAttendingReception: "no",
receptionPartySize: 0,
isAttendingShinzenshiki: "no",
shinzenshikiPartySize: 0,
isAttendingHiroen: "no",
hiroenPartySize: 0,
lastRSVPUpdateTime: "2024-05-26 10:00",
partyMembers:"avani",
allergies:"none"
},
{
guest_id:"aswed186",
name:"???",
email:"kajita.shun.dev@gmail.com",
password:"fionashome301",
ReceptionOnly: false,
SangeetReceptionOnly: false,
SanMuhRec: false,
AllEvents: false,
AllUSJapan: false,
isAttendingMehendi: "no",
mehendiPartySize: 0,
isAttendingHaldi: "no",
haldiPartySize: 0,
isAttendingSangeet: "no",
sangeetPartySize: 0,
isAttendingMuhurtham: "no",
muhurthamPartySize: 0,
isAttendingReception: "no",
receptionPartySize: 0,
isAttendingShinzenshiki: "no",
shinzenshikiPartySize: 0,
isAttendingHiroen: "no",
hiroenPartySize: 0,
lastRSVPUpdateTime: "2024-05-26 10:00",
partyMembers:"avani",
allergies:"none"
},
{
guest_id:"aswed187",
name:"???",
email:"s.shiori1014pf@gmail.com",
password:"fionashome301",
ReceptionOnly: false,
SangeetReceptionOnly: false,
SanMuhRec: false,
AllEvents: false,
AllUSJapan: false,
isAttendingMehendi: "no",
mehendiPartySize: 0,
isAttendingHaldi: "no",
haldiPartySize: 0,
isAttendingSangeet: "no",
sangeetPartySize: 0,
isAttendingMuhurtham: "no",
muhurthamPartySize: 0,
isAttendingReception: "no",
receptionPartySize: 0,
isAttendingShinzenshiki: "no",
shinzenshikiPartySize: 0,
isAttendingHiroen: "no",
hiroenPartySize: 0,
lastRSVPUpdateTime: "2024-05-26 10:00",
partyMembers:"avani",
allergies:"none"
},
{
guest_id:"aswed188",
name:"???",
email:"tokuu1226@gmail.com",
password:"fionashome301",
ReceptionOnly: false,
SangeetReceptionOnly: false,
SanMuhRec: false,
AllEvents: false,
AllUSJapan: false,
isAttendingMehendi: "no",
mehendiPartySize: 0,
isAttendingHaldi: "no",
haldiPartySize: 0,
isAttendingSangeet: "no",
sangeetPartySize: 0,
isAttendingMuhurtham: "no",
muhurthamPartySize: 0,
isAttendingReception: "no",
receptionPartySize: 0,
isAttendingShinzenshiki: "no",
shinzenshikiPartySize: 0,
isAttendingHiroen: "no",
hiroenPartySize: 0,
lastRSVPUpdateTime: "2024-05-26 10:00",
partyMembers:"avani",
allergies:"none"
},
{
guest_id:"aswed189",
name:"?????",
email:"naoya.nishiwaki.tti@gmail.com",
password:"fionashome301",
ReceptionOnly: false,
SangeetReceptionOnly: false,
SanMuhRec: false,
AllEvents: false,
AllUSJapan: false,
isAttendingMehendi: "no",
mehendiPartySize: 0,
isAttendingHaldi: "no",
haldiPartySize: 0,
isAttendingSangeet: "no",
sangeetPartySize: 0,
isAttendingMuhurtham: "no",
muhurthamPartySize: 0,
isAttendingReception: "no",
receptionPartySize: 0,
isAttendingShinzenshiki: "no",
shinzenshikiPartySize: 0,
isAttendingHiroen: "no",
hiroenPartySize: 0,
lastRSVPUpdateTime: "2024-05-26 10:00",
partyMembers:"avani",
allergies:"none"
},
{
guest_id:"aswed190",
name:"????",
email:"akisame466@gmail.com",
password:"fionashome301",
ReceptionOnly: false,
SangeetReceptionOnly: false,
SanMuhRec: false,
AllEvents: false,
AllUSJapan: false,
isAttendingMehendi: "no",
mehendiPartySize: 0,
isAttendingHaldi: "no",
haldiPartySize: 0,
isAttendingSangeet: "no",
sangeetPartySize: 0,
isAttendingMuhurtham: "no",
muhurthamPartySize: 0,
isAttendingReception: "no",
receptionPartySize: 0,
isAttendingShinzenshiki: "no",
shinzenshikiPartySize: 0,
isAttendingHiroen: "no",
hiroenPartySize: 0,
lastRSVPUpdateTime: "2024-05-26 10:00",
partyMembers:"avani",
allergies:"none"
},
{
guest_id:"aswed191",
name:"?????",
email:"chiyochibi321@gmail.com",
password:"fionashome301",
ReceptionOnly: false,
SangeetReceptionOnly: false,
SanMuhRec: false,
AllEvents: false,
AllUSJapan: false,
isAttendingMehendi: "no",
mehendiPartySize: 0,
isAttendingHaldi: "no",
haldiPartySize: 0,
isAttendingSangeet: "no",
sangeetPartySize: 0,
isAttendingMuhurtham: "no",
muhurthamPartySize: 0,
isAttendingReception: "no",
receptionPartySize: 0,
isAttendingShinzenshiki: "no",
shinzenshikiPartySize: 0,
isAttendingHiroen: "no",
hiroenPartySize: 0,
lastRSVPUpdateTime: "2024-05-26 10:00",
partyMembers:"avani",
allergies:"none"
},
{
guest_id:"aswed192",
name:"???",
email:"kajita.shun.dev@gmail.com",
password:"fionashome301",
ReceptionOnly: false,
SangeetReceptionOnly: false,
SanMuhRec: false,
AllEvents: false,
AllUSJapan: false,
isAttendingMehendi: "no",
mehendiPartySize: 0,
isAttendingHaldi: "no",
haldiPartySize: 0,
isAttendingSangeet: "no",
sangeetPartySize: 0,
isAttendingMuhurtham: "no",
muhurthamPartySize: 0,
isAttendingReception: "no",
receptionPartySize: 0,
isAttendingShinzenshiki: "no",
shinzenshikiPartySize: 0,
isAttendingHiroen: "no",
hiroenPartySize: 0,
lastRSVPUpdateTime: "2024-05-26 10:00",
partyMembers:"avani",
allergies:"none"
},
{
guest_id:"aswed193",
name:"?????",
email:"ymnaturalheart@gmail.com",
password:"fionashome301",
ReceptionOnly: false,
SangeetReceptionOnly: false,
SanMuhRec: false,
AllEvents: false,
AllUSJapan: false,
isAttendingMehendi: "no",
mehendiPartySize: 0,
isAttendingHaldi: "no",
haldiPartySize: 0,
isAttendingSangeet: "no",
sangeetPartySize: 0,
isAttendingMuhurtham: "no",
muhurthamPartySize: 0,
isAttendingReception: "no",
receptionPartySize: 0,
isAttendingShinzenshiki: "no",
shinzenshikiPartySize: 0,
isAttendingHiroen: "no",
hiroenPartySize: 0,
lastRSVPUpdateTime: "2024-05-26 10:00",
partyMembers:"avani",
allergies:"none"
},
{
guest_id:"aswed194",
name:"????",
email:"t.shaska.j@gmail.com",
password:"fionashome301",
ReceptionOnly: false,
SangeetReceptionOnly: false,
SanMuhRec: false,
AllEvents: false,
AllUSJapan: false,
isAttendingMehendi: "no",
mehendiPartySize: 0,
isAttendingHaldi: "no",
haldiPartySize: 0,
isAttendingSangeet: "no",
sangeetPartySize: 0,
isAttendingMuhurtham: "no",
muhurthamPartySize: 0,
isAttendingReception: "no",
receptionPartySize: 0,
isAttendingShinzenshiki: "no",
shinzenshikiPartySize: 0,
isAttendingHiroen: "no",
hiroenPartySize: 0,
lastRSVPUpdateTime: "2024-05-26 10:00",
partyMembers:"avani",
allergies:"none"
},
{
guest_id:"aswed195",
name:"??????",
email:"kiyo410810sid@gmail.com",
password:"fionashome301",
ReceptionOnly: false,
SangeetReceptionOnly: false,
SanMuhRec: false,
AllEvents: false,
AllUSJapan: false,
isAttendingMehendi: "no",
mehendiPartySize: 0,
isAttendingHaldi: "no",
haldiPartySize: 0,
isAttendingSangeet: "no",
sangeetPartySize: 0,
isAttendingMuhurtham: "no",
muhurthamPartySize: 0,
isAttendingReception: "no",
receptionPartySize: 0,
isAttendingShinzenshiki: "no",
shinzenshikiPartySize: 0,
isAttendingHiroen: "no",
hiroenPartySize: 0,
lastRSVPUpdateTime: "2024-05-26 10:00",
partyMembers:"avani",
allergies:"none"
},
{
guest_id:"aswed196",
name:"?? ?",
email:"meki46bit@gmail.com",
password:"fionashome301",
ReceptionOnly: false,
SangeetReceptionOnly: false,
SanMuhRec: false,
AllEvents: false,
AllUSJapan: false,
isAttendingMehendi: "no",
mehendiPartySize: 0,
isAttendingHaldi: "no",
haldiPartySize: 0,
isAttendingSangeet: "no",
sangeetPartySize: 0,
isAttendingMuhurtham: "no",
muhurthamPartySize: 0,
isAttendingReception: "no",
receptionPartySize: 0,
isAttendingShinzenshiki: "no",
shinzenshikiPartySize: 0,
isAttendingHiroen: "no",
hiroenPartySize: 0,
lastRSVPUpdateTime: "2024-05-26 10:00",
partyMembers:"avani",
allergies:"none"
},
{
guest_id:"aswed197",
name:"???",
email:"horikatta.same@gmail.com",
password:"fionashome301",
ReceptionOnly: false,
SangeetReceptionOnly: false,
SanMuhRec: false,
AllEvents: false,
AllUSJapan: false,
isAttendingMehendi: "no",
mehendiPartySize: 0,
isAttendingHaldi: "no",
haldiPartySize: 0,
isAttendingSangeet: "no",
sangeetPartySize: 0,
isAttendingMuhurtham: "no",
muhurthamPartySize: 0,
isAttendingReception: "no",
receptionPartySize: 0,
isAttendingShinzenshiki: "no",
shinzenshikiPartySize: 0,
isAttendingHiroen: "no",
hiroenPartySize: 0,
lastRSVPUpdateTime: "2024-05-26 10:00",
partyMembers:"avani",
allergies:"none"
},
{
guest_id:"aswed198",
name:"????",
email:"akihiro.watanabe@gmail.com",
password:"fionashome301",
ReceptionOnly: false,
SangeetReceptionOnly: false,
SanMuhRec: false,
AllEvents: false,
AllUSJapan: false,
isAttendingMehendi: "no",
mehendiPartySize: 0,
isAttendingHaldi: "no",
haldiPartySize: 0,
isAttendingSangeet: "no",
sangeetPartySize: 0,
isAttendingMuhurtham: "no",
muhurthamPartySize: 0,
isAttendingReception: "no",
receptionPartySize: 0,
isAttendingShinzenshiki: "no",
shinzenshikiPartySize: 0,
isAttendingHiroen: "no",
hiroenPartySize: 0,
lastRSVPUpdateTime: "2024-05-26 10:00",
partyMembers:"avani",
allergies:"none"
},
{
guest_id:"aswed199",
name:"??????",
email:"osushitabetai08@gmail.com",
password:"fionashome301",
ReceptionOnly: false,
SangeetReceptionOnly: false,
SanMuhRec: false,
AllEvents: false,
AllUSJapan: false,
isAttendingMehendi: "no",
mehendiPartySize: 0,
isAttendingHaldi: "no",
haldiPartySize: 0,
isAttendingSangeet: "no",
sangeetPartySize: 0,
isAttendingMuhurtham: "no",
muhurthamPartySize: 0,
isAttendingReception: "no",
receptionPartySize: 0,
isAttendingShinzenshiki: "no",
shinzenshikiPartySize: 0,
isAttendingHiroen: "no",
hiroenPartySize: 0,
lastRSVPUpdateTime: "2024-05-26 10:00",
partyMembers:"avani",
allergies:"none"
},
{
guest_id:"aswed200",
name:"????",
email:"enryznphpe@i.softbank.jp",
password:"fionashome301",
ReceptionOnly: false,
SangeetReceptionOnly: false,
SanMuhRec: false,
AllEvents: false,
AllUSJapan: false,
isAttendingMehendi: "no",
mehendiPartySize: 0,
isAttendingHaldi: "no",
haldiPartySize: 0,
isAttendingSangeet: "no",
sangeetPartySize: 0,
isAttendingMuhurtham: "no",
muhurthamPartySize: 0,
isAttendingReception: "no",
receptionPartySize: 0,
isAttendingShinzenshiki: "no",
shinzenshikiPartySize: 0,
isAttendingHiroen: "no",
hiroenPartySize: 0,
lastRSVPUpdateTime: "2024-05-26 10:00",
partyMembers:"avani",
allergies:"none"
},
{
guest_id:"aswed201",
name:"????",
email:"nisikisdvx@gmail.com",
password:"fionashome301",
ReceptionOnly: false,
SangeetReceptionOnly: false,
SanMuhRec: false,
AllEvents: false,
AllUSJapan: false,
isAttendingMehendi: "no",
mehendiPartySize: 0,
isAttendingHaldi: "no",
haldiPartySize: 0,
isAttendingSangeet: "no",
sangeetPartySize: 0,
isAttendingMuhurtham: "no",
muhurthamPartySize: 0,
isAttendingReception: "no",
receptionPartySize: 0,
isAttendingShinzenshiki: "no",
shinzenshikiPartySize: 0,
isAttendingHiroen: "no",
hiroenPartySize: 0,
lastRSVPUpdateTime: "2024-05-26 10:00",
partyMembers:"avani",
allergies:"none"
},
{
guest_id:"aswed202",
name:"??????",
email:"kiyo410810sid@gmail.com",
password:"fionashome301",
ReceptionOnly: false,
SangeetReceptionOnly: false,
SanMuhRec: false,
AllEvents: false,
AllUSJapan: false,
isAttendingMehendi: "no",
mehendiPartySize: 0,
isAttendingHaldi: "no",
haldiPartySize: 0,
isAttendingSangeet: "no",
sangeetPartySize: 0,
isAttendingMuhurtham: "no",
muhurthamPartySize: 0,
isAttendingReception: "no",
receptionPartySize: 0,
isAttendingShinzenshiki: "no",
shinzenshikiPartySize: 0,
isAttendingHiroen: "no",
hiroenPartySize: 0,
lastRSVPUpdateTime: "2024-05-26 10:00",
partyMembers:"avani",
allergies:"none"
},
{
guest_id:"aswed203",
name:"????",
email:"ujishi-shooting-ndnl@i.softbank.jp",
password:"fionashome301",
ReceptionOnly: false,
SangeetReceptionOnly: false,
SanMuhRec: false,
AllEvents: false,
AllUSJapan: false,
isAttendingMehendi: "no",
mehendiPartySize: 0,
isAttendingHaldi: "no",
haldiPartySize: 0,
isAttendingSangeet: "no",
sangeetPartySize: 0,
isAttendingMuhurtham: "no",
muhurthamPartySize: 0,
isAttendingReception: "no",
receptionPartySize: 0,
isAttendingShinzenshiki: "no",
shinzenshikiPartySize: 0,
isAttendingHiroen: "no",
hiroenPartySize: 0,
lastRSVPUpdateTime: "2024-05-26 10:00",
partyMembers:"avani",
allergies:"none"
},
{
guest_id:"aswed204",
name:"?????",
email:"boncyan1010@gmail.com",
password:"fionashome301",
ReceptionOnly: false,
SangeetReceptionOnly: false,
SanMuhRec: false,
AllEvents: false,
AllUSJapan: false,
isAttendingMehendi: "no",
mehendiPartySize: 0,
isAttendingHaldi: "no",
haldiPartySize: 0,
isAttendingSangeet: "no",
sangeetPartySize: 0,
isAttendingMuhurtham: "no",
muhurthamPartySize: 0,
isAttendingReception: "no",
receptionPartySize: 0,
isAttendingShinzenshiki: "no",
shinzenshikiPartySize: 0,
isAttendingHiroen: "no",
hiroenPartySize: 0,
lastRSVPUpdateTime: "2024-05-26 10:00",
partyMembers:"avani",
allergies:"none"
},
{
guest_id:"aswed205",
name:"Mandar Uncle & Nilima Aunty",
email:"nan",
password:"fionashome301",
ReceptionOnly: false,
SangeetReceptionOnly: false,
SanMuhRec: false,
AllEvents: false,
AllUSJapan: false,
isAttendingMehendi: "no",
mehendiPartySize: 0,
isAttendingHaldi: "no",
haldiPartySize: 0,
isAttendingSangeet: "no",
sangeetPartySize: 0,
isAttendingMuhurtham: "no",
muhurthamPartySize: 0,
isAttendingReception: "no",
receptionPartySize: 0,
isAttendingShinzenshiki: "no",
shinzenshikiPartySize: 0,
isAttendingHiroen: "no",
hiroenPartySize: 0,
lastRSVPUpdateTime: "2024-05-26 10:00",
partyMembers:"avani",
allergies:"none"
},
]
