const new_guest_1 = 
[
	{
		guest_id: "aswed157",
		name: "Arvind Saraff",
		email: "aravind.saraff@gmail.com",
		password: "fionashome301",
		ReceptionOnly: false,
		SangeetReceptionOnly: false,
		SanMuhRec: false,
		AllEvents: true,
		AllUSJapan: false,
		isAttendingMehendi: "no",
		mehendiPartySize: 0,
		isAttendingHaldi: "no",
		haldiPartySize: 0,
		isAttendingSangeet: "no",
		sangeetPartySize: 0,
		isAttendingMuhurtham: "no",
		muhurthamPartySize: 0,
		isAttendingReception: "no",
		receptionPartySize: 0,
		isAttendingShinzenshiki: "no",
		shinzenshikiPartySize: 0,
		isAttendingHiroen: "no",
		hiroenPartySize: 0,
		lastRSVPUpdateTime: "2024-05-26 10:00",
		partyMembers: "avani",
		allergies: "none",
		hasRSVPed: false,
	},
	{
		guest_id: "aswed158",
		name: "Sowmya (SFO)",
		email: "soumyab@gmail.com",
		password: "fionashome301",
		ReceptionOnly: false,
		SangeetReceptionOnly: false,
		SanMuhRec: false,
		AllEvents: true,
		AllUSJapan: false,
		isAttendingMehendi: "no",
		mehendiPartySize: 0,
		isAttendingHaldi: "no",
		haldiPartySize: 0,
		isAttendingSangeet: "no",
		sangeetPartySize: 0,
		isAttendingMuhurtham: "no",
		muhurthamPartySize: 0,
		isAttendingReception: "no",
		receptionPartySize: 0,
		isAttendingShinzenshiki: "no",
		shinzenshikiPartySize: 0,
		isAttendingHiroen: "no",
		hiroenPartySize: 0,
		lastRSVPUpdateTime: "2024-05-26 10:00",
		partyMembers: "avani",
		allergies: "none",
		hasRSVPed: false,
	},
	{
		guest_id: "aswed159",
		name: "Usha & Ganesh",
		email: "ushaganesh@verizon.net",
		password: "fionashome301",
		ReceptionOnly: false,
		SangeetReceptionOnly: false,
		SanMuhRec: true,
		AllEvents: false,
		AllUSJapan: false,
		isAttendingMehendi: "no",
		mehendiPartySize: 0,
		isAttendingHaldi: "no",
		haldiPartySize: 0,
		isAttendingSangeet: "no",
		sangeetPartySize: 0,
		isAttendingMuhurtham: "no",
		muhurthamPartySize: 0,
		isAttendingReception: "no",
		receptionPartySize: 0,
		isAttendingShinzenshiki: "no",
		shinzenshikiPartySize: 0,
		isAttendingHiroen: "no",
		hiroenPartySize: 0,
		lastRSVPUpdateTime: "2024-05-26 10:00",
		partyMembers: "avani",
		allergies: "none",
		hasRSVPed: false,
	},
	{
		guest_id: "aswed160",
		name: "Sujatha",
		email: "sujatha.anandan@gmail.com",
		password: "fionashome301",
		ReceptionOnly: false,
		SangeetReceptionOnly: false,
		SanMuhRec: true,
		AllEvents: false,
		AllUSJapan: false,
		isAttendingMehendi: "no",
		mehendiPartySize: 0,
		isAttendingHaldi: "no",
		haldiPartySize: 0,
		isAttendingSangeet: "no",
		sangeetPartySize: 0,
		isAttendingMuhurtham: "no",
		muhurthamPartySize: 0,
		isAttendingReception: "no",
		receptionPartySize: 0,
		isAttendingShinzenshiki: "no",
		shinzenshikiPartySize: 0,
		isAttendingHiroen: "no",
		hiroenPartySize: 0,
		lastRSVPUpdateTime: "2024-05-26 10:00",
		partyMembers: "avani",
		allergies: "none",
		hasRSVPed: false,
	},
	{
		guest_id: "aswed161",
		name: "Swapna & Shobit Jain",
		email: "csupna@hotmail.com",
		password: "fionashome301",
		ReceptionOnly: false,
		SangeetReceptionOnly: false,
		SanMuhRec: true,
		AllEvents: false,
		AllUSJapan: false,
		isAttendingMehendi: "no",
		mehendiPartySize: 0,
		isAttendingHaldi: "no",
		haldiPartySize: 0,
		isAttendingSangeet: "no",
		sangeetPartySize: 0,
		isAttendingMuhurtham: "no",
		muhurthamPartySize: 0,
		isAttendingReception: "no",
		receptionPartySize: 0,
		isAttendingShinzenshiki: "no",
		shinzenshikiPartySize: 0,
		isAttendingHiroen: "no",
		hiroenPartySize: 0,
		lastRSVPUpdateTime: "2024-05-26 10:00",
		partyMembers: "avani",
		allergies: "none",
		hasRSVPed: false,
	},
	{
		guest_id: "aswed162",
		name: "Vish Baliga",
		email: "vbaliga60@gmail.com",
		password: "fionashome301",
		ReceptionOnly: false,
		SangeetReceptionOnly: false,
		SanMuhRec: true,
		AllEvents: false,
		AllUSJapan: false,
		isAttendingMehendi: "no",
		mehendiPartySize: 0,
		isAttendingHaldi: "no",
		haldiPartySize: 0,
		isAttendingSangeet: "no",
		sangeetPartySize: 0,
		isAttendingMuhurtham: "no",
		muhurthamPartySize: 0,
		isAttendingReception: "no",
		receptionPartySize: 0,
		isAttendingShinzenshiki: "no",
		shinzenshikiPartySize: 0,
		isAttendingHiroen: "no",
		hiroenPartySize: 0,
		lastRSVPUpdateTime: "2024-05-26 10:00",
		partyMembers: "avani",
		allergies: "none",
		hasRSVPed: false,
	},
	{
		guest_id: "aswed163",
		name: "Sanjay & Seema Baliga",
		email: "sanjay.baliga@gmail.com",
		password: "fionashome301",
		ReceptionOnly: false,
		SangeetReceptionOnly: false,
		SanMuhRec: true,
		AllEvents: false,
		AllUSJapan: false,
		isAttendingMehendi: "no",
		mehendiPartySize: 0,
		isAttendingHaldi: "no",
		haldiPartySize: 0,
		isAttendingSangeet: "no",
		sangeetPartySize: 0,
		isAttendingMuhurtham: "no",
		muhurthamPartySize: 0,
		isAttendingReception: "no",
		receptionPartySize: 0,
		isAttendingShinzenshiki: "no",
		shinzenshikiPartySize: 0,
		isAttendingHiroen: "no",
		hiroenPartySize: 0,
		lastRSVPUpdateTime: "2024-05-26 10:00",
		partyMembers: "avani",
		allergies: "none",
		hasRSVPed: false,
	},
	{
		guest_id: "aswed164",
		name: "Mait & Arup",
		email: "maitreyee.raha@gmail.com",
		password: "fionashome301",
		ReceptionOnly: false,
		SangeetReceptionOnly: false,
		SanMuhRec: true,
		AllEvents: false,
		AllUSJapan: false,
		isAttendingMehendi: "no",
		mehendiPartySize: 0,
		isAttendingHaldi: "no",
		haldiPartySize: 0,
		isAttendingSangeet: "no",
		sangeetPartySize: 0,
		isAttendingMuhurtham: "no",
		muhurthamPartySize: 0,
		isAttendingReception: "no",
		receptionPartySize: 0,
		isAttendingShinzenshiki: "no",
		shinzenshikiPartySize: 0,
		isAttendingHiroen: "no",
		hiroenPartySize: 0,
		lastRSVPUpdateTime: "2024-05-26 10:00",
		partyMembers: "avani",
		allergies: "none",
		hasRSVPed: false,
	},
	{
		guest_id: "aswed165",
		name: "Sripriya & Sendil",
		email: "shripriya.shripriyas@hotmail.com",
		password: "fionashome301",
		ReceptionOnly: false,
		SangeetReceptionOnly: false,
		SanMuhRec: true,
		AllEvents: false,
		AllUSJapan: false,
		isAttendingMehendi: "no",
		mehendiPartySize: 0,
		isAttendingHaldi: "no",
		haldiPartySize: 0,
		isAttendingSangeet: "no",
		sangeetPartySize: 0,
		isAttendingMuhurtham: "no",
		muhurthamPartySize: 0,
		isAttendingReception: "no",
		receptionPartySize: 0,
		isAttendingShinzenshiki: "no",
		shinzenshikiPartySize: 0,
		isAttendingHiroen: "no",
		hiroenPartySize: 0,
		lastRSVPUpdateTime: "2024-05-26 10:00",
		partyMembers: "avani",
		allergies: "none",
		hasRSVPed: false,
	},
	{
		guest_id: "aswed166",
		name: "Durai & Chandrakala",
		email: "rdurai@gmail.com",
		password: "fionashome301",
		ReceptionOnly: false,
		SangeetReceptionOnly: false,
		SanMuhRec: true,
		AllEvents: false,
		AllUSJapan: false,
		isAttendingMehendi: "no",
		mehendiPartySize: 0,
		isAttendingHaldi: "no",
		haldiPartySize: 0,
		isAttendingSangeet: "no",
		sangeetPartySize: 0,
		isAttendingMuhurtham: "no",
		muhurthamPartySize: 0,
		isAttendingReception: "no",
		receptionPartySize: 0,
		isAttendingShinzenshiki: "no",
		shinzenshikiPartySize: 0,
		isAttendingHiroen: "no",
		hiroenPartySize: 0,
		lastRSVPUpdateTime: "2024-05-26 10:00",
		partyMembers: "avani",
		allergies: "none",
		hasRSVPed: false,
	},
	{
		guest_id: "aswed167",
		name: "John Sandala",
		email: "john@edifytech.us",
		password: "fionashome301",
		ReceptionOnly: false,
		SangeetReceptionOnly: false,
		SanMuhRec: true,
		AllEvents: false,
		AllUSJapan: false,
		isAttendingMehendi: "no",
		mehendiPartySize: 0,
		isAttendingHaldi: "no",
		haldiPartySize: 0,
		isAttendingSangeet: "no",
		sangeetPartySize: 0,
		isAttendingMuhurtham: "no",
		muhurthamPartySize: 0,
		isAttendingReception: "no",
		receptionPartySize: 0,
		isAttendingShinzenshiki: "no",
		shinzenshikiPartySize: 0,
		isAttendingHiroen: "no",
		hiroenPartySize: 0,
		lastRSVPUpdateTime: "2024-05-26 10:00",
		partyMembers: "avani",
		allergies: "none",
		hasRSVPed: false,
	},
	{
		guest_id: "aswed168",
		name: "Natasha ",
		email: "natasha@edifytech.us",
		password: "fionashome301",
		ReceptionOnly: false,
		SangeetReceptionOnly: false,
		SanMuhRec: true,
		AllEvents: false,
		AllUSJapan: false,
		isAttendingMehendi: "no",
		mehendiPartySize: 0,
		isAttendingHaldi: "no",
		haldiPartySize: 0,
		isAttendingSangeet: "no",
		sangeetPartySize: 0,
		isAttendingMuhurtham: "no",
		muhurthamPartySize: 0,
		isAttendingReception: "no",
		receptionPartySize: 0,
		isAttendingShinzenshiki: "no",
		shinzenshikiPartySize: 0,
		isAttendingHiroen: "no",
		hiroenPartySize: 0,
		lastRSVPUpdateTime: "2024-05-26 10:00",
		partyMembers: "avani",
		allergies: "none",
		hasRSVPed: false,
	},
	{
		guest_id: "aswed169",
		name: "Ravi Rao",
		email: "rsrao@valuemomentum.com",
		password: "fionashome301",
		ReceptionOnly: true,
		SangeetReceptionOnly: false,
		SanMuhRec: false,
		AllEvents: false,
		AllUSJapan: false,
		isAttendingMehendi: "no",
		mehendiPartySize: 0,
		isAttendingHaldi: "no",
		haldiPartySize: 0,
		isAttendingSangeet: "no",
		sangeetPartySize: 0,
		isAttendingMuhurtham: "no",
		muhurthamPartySize: 0,
		isAttendingReception: "no",
		receptionPartySize: 0,
		isAttendingShinzenshiki: "no",
		shinzenshikiPartySize: 0,
		isAttendingHiroen: "no",
		hiroenPartySize: 0,
		lastRSVPUpdateTime: "2024-05-26 10:00",
		partyMembers: "avani",
		allergies: "none",
		hasRSVPed: false,
	},
	{
		guest_id: "aswed170",
		name: "Anant Iyer",
		email: "anant.iyer@valuemomentum.com",
		password: "fionashome301",
		ReceptionOnly: true,
		SangeetReceptionOnly: false,
		SanMuhRec: false,
		AllEvents: false,
		AllUSJapan: false,
		isAttendingMehendi: "no",
		mehendiPartySize: 0,
		isAttendingHaldi: "no",
		haldiPartySize: 0,
		isAttendingSangeet: "no",
		sangeetPartySize: 0,
		isAttendingMuhurtham: "no",
		muhurthamPartySize: 0,
		isAttendingReception: "no",
		receptionPartySize: 0,
		isAttendingShinzenshiki: "no",
		shinzenshikiPartySize: 0,
		isAttendingHiroen: "no",
		hiroenPartySize: 0,
		lastRSVPUpdateTime: "2024-05-26 10:00",
		partyMembers: "avani",
		allergies: "none",
		hasRSVPed: false,
	},
	{
		guest_id: "aswed171",
		name: "Jayesh Chauhan",
		email: "jayesh.chauhan@valuemomentum.com",
		password: "fionashome301",
		ReceptionOnly: true,
		SangeetReceptionOnly: false,
		SanMuhRec: false,
		AllEvents: false,
		AllUSJapan: false,
		isAttendingMehendi: "no",
		mehendiPartySize: 0,
		isAttendingHaldi: "no",
		haldiPartySize: 0,
		isAttendingSangeet: "no",
		sangeetPartySize: 0,
		isAttendingMuhurtham: "no",
		muhurthamPartySize: 0,
		isAttendingReception: "no",
		receptionPartySize: 0,
		isAttendingShinzenshiki: "no",
		shinzenshikiPartySize: 0,
		isAttendingHiroen: "no",
		hiroenPartySize: 0,
		lastRSVPUpdateTime: "2024-05-26 10:00",
		partyMembers: "avani",
		allergies: "none",
		hasRSVPed: false,
	},
	{
		guest_id: "aswed172",
		name: "Srini Vasi Reddy",
		email: "svasireddy@valuemomentum.com",
		password: "fionashome301",
		ReceptionOnly: true,
		SangeetReceptionOnly: false,
		SanMuhRec: false,
		AllEvents: false,
		AllUSJapan: false,
		isAttendingMehendi: "no",
		mehendiPartySize: 0,
		isAttendingHaldi: "no",
		haldiPartySize: 0,
		isAttendingSangeet: "no",
		sangeetPartySize: 0,
		isAttendingMuhurtham: "no",
		muhurthamPartySize: 0,
		isAttendingReception: "no",
		receptionPartySize: 0,
		isAttendingShinzenshiki: "no",
		shinzenshikiPartySize: 0,
		isAttendingHiroen: "no",
		hiroenPartySize: 0,
		lastRSVPUpdateTime: "2024-05-26 10:00",
		partyMembers: "avani",
		allergies: "none",
		hasRSVPed: false,
	},
	{
		guest_id: "aswed173",
		name: "Shirley & Don Novarro",
		email: "shirley_uic@yahoo.com",
		password: "fionashome301",
		ReceptionOnly: true,
		SangeetReceptionOnly: false,
		SanMuhRec: false,
		AllEvents: false,
		AllUSJapan: false,
		isAttendingMehendi: "no",
		mehendiPartySize: 0,
		isAttendingHaldi: "no",
		haldiPartySize: 0,
		isAttendingSangeet: "no",
		sangeetPartySize: 0,
		isAttendingMuhurtham: "no",
		muhurthamPartySize: 0,
		isAttendingReception: "no",
		receptionPartySize: 0,
		isAttendingShinzenshiki: "no",
		shinzenshikiPartySize: 0,
		isAttendingHiroen: "no",
		hiroenPartySize: 0,
		lastRSVPUpdateTime: "2024-05-26 10:00",
		partyMembers: "avani",
		allergies: "none",
		hasRSVPed: false,
	},
	{
		guest_id: "aswed174",
		name: "Seina & Imad",
		email: "imad.arain@gmail.com",
		password: "fionashome301",
		ReceptionOnly: true,
		SangeetReceptionOnly: false,
		SanMuhRec: false,
		AllEvents: false,
		AllUSJapan: false,
		isAttendingMehendi: "no",
		mehendiPartySize: 0,
		isAttendingHaldi: "no",
		haldiPartySize: 0,
		isAttendingSangeet: "no",
		sangeetPartySize: 0,
		isAttendingMuhurtham: "no",
		muhurthamPartySize: 0,
		isAttendingReception: "no",
		receptionPartySize: 0,
		isAttendingShinzenshiki: "no",
		shinzenshikiPartySize: 0,
		isAttendingHiroen: "no",
		hiroenPartySize: 0,
		lastRSVPUpdateTime: "2024-05-26 10:00",
		partyMembers: "avani",
		allergies: "none",
		hasRSVPed: false,
	},
	{
		guest_id: "aswed175",
		name: "Greg H & Cindy",
		email: "hagermang@aol.com",
		password: "fionashome301",
		ReceptionOnly: true,
		SangeetReceptionOnly: false,
		SanMuhRec: false,
		AllEvents: false,
		AllUSJapan: false,
		isAttendingMehendi: "no",
		mehendiPartySize: 0,
		isAttendingHaldi: "no",
		haldiPartySize: 0,
		isAttendingSangeet: "no",
		sangeetPartySize: 0,
		isAttendingMuhurtham: "no",
		muhurthamPartySize: 0,
		isAttendingReception: "no",
		receptionPartySize: 0,
		isAttendingShinzenshiki: "no",
		shinzenshikiPartySize: 0,
		isAttendingHiroen: "no",
		hiroenPartySize: 0,
		lastRSVPUpdateTime: "2024-05-26 10:00",
		partyMembers: "avani",
		allergies: "none",
		hasRSVPed: false,
	},
	{
		guest_id: "aswed176",
		name: "Phaly & Arkadius",
		email: "phaly.pichota@gmail.com",
		password: "fionashome301",
		ReceptionOnly: true,
		SangeetReceptionOnly: false,
		SanMuhRec: false,
		AllEvents: false,
		AllUSJapan: false,
		isAttendingMehendi: "no",
		mehendiPartySize: 0,
		isAttendingHaldi: "no",
		haldiPartySize: 0,
		isAttendingSangeet: "no",
		sangeetPartySize: 0,
		isAttendingMuhurtham: "no",
		muhurthamPartySize: 0,
		isAttendingReception: "no",
		receptionPartySize: 0,
		isAttendingShinzenshiki: "no",
		shinzenshikiPartySize: 0,
		isAttendingHiroen: "no",
		hiroenPartySize: 0,
		lastRSVPUpdateTime: "2024-05-26 10:00",
		partyMembers: "avani",
		allergies: "none",
		hasRSVPed: false,
	},
]

module.exports = {
	new_guest_1
};