const new_guest_1 = 
[
	{
		guest_id: "aswed202",
		name: "Mandar Ponkshe",
		email: "mandar_ponkshe@yahoo.com",
		password: "fionashome301",
		ReceptionOnly: false,
		SangeetReceptionOnly: false,
		SanMuhRec: false,
		AllEvents: false,
		AllUSJapan: false,
		JapanOnly: true,
		isAttendingMehendi: "no",
		mehendiPartySize: 0,
		isAttendingHaldi: "no",
		haldiPartySize: 0,
		isAttendingSangeet: "no",
		sangeetPartySize: 0,
		isAttendingMuhurtham: "no",
		muhurthamPartySize: 0,
		isAttendingReception: "no",
		receptionPartySize: 0,
		isAttendingShinzenshiki: "no",
		shinzenshikiPartySize: 0,
		isAttendingHiroen: "no",
		hiroenPartySize: 0,
		lastRSVPUpdateTime: "2024-05-26 10:00",
		partyMembers: "avani",
		allergies: "none"
	},
	{
		guest_id: "aswed203",
		name: "Nilima Ponkshe",
		email: "nilima_ponkshe@yahoo.com",
		password: "fionashome301",
		ReceptionOnly: false,
		SangeetReceptionOnly: false,
		SanMuhRec: false,
		AllEvents: false,
		AllUSJapan: false,
		JapanOnly: true,
		isAttendingMehendi: "no",
		mehendiPartySize: 0,
		isAttendingHaldi: "no",
		haldiPartySize: 0,
		isAttendingSangeet: "no",
		sangeetPartySize: 0,
		isAttendingMuhurtham: "no",
		muhurthamPartySize: 0,
		isAttendingReception: "no",
		receptionPartySize: 0,
		isAttendingShinzenshiki: "no",
		shinzenshikiPartySize: 0,
		isAttendingHiroen: "no",
		hiroenPartySize: 0,
		lastRSVPUpdateTime: "2024-05-26 10:00",
		partyMembers: "avani",
		allergies: "none"
	},
	{
		guest_id: "aswed204",
		name: "Sohan Prabhu",
		email: "sohanprabhu.jp@gmail.com",
		password: "fionashome301",
		ReceptionOnly: false,
		SangeetReceptionOnly: false,
		SanMuhRec: false,
		AllEvents: false,
		AllUSJapan: false,
		JapanOnly: true,
		isAttendingMehendi: "no",
		mehendiPartySize: 0,
		isAttendingHaldi: "no",
		haldiPartySize: 0,
		isAttendingSangeet: "no",
		sangeetPartySize: 0,
		isAttendingMuhurtham: "no",
		muhurthamPartySize: 0,
		isAttendingReception: "no",
		receptionPartySize: 0,
		isAttendingShinzenshiki: "no",
		shinzenshikiPartySize: 0,
		isAttendingHiroen: "no",
		hiroenPartySize: 0,
		lastRSVPUpdateTime: "2024-05-26 10:00",
		partyMembers: "avani",
		allergies: "none"
	},
	{
		guest_id: "aswed205",
		name: "Vivek & Mounika Mogalapalli",
		email: "itsvivekm@outlook.com",
		password: "fionashome301",
		ReceptionOnly: false,
		SangeetReceptionOnly: false,
		SanMuhRec: false,
		AllEvents: false,
		AllUSJapan: true,
		JapanOnly: false,
		isAttendingMehendi: "no",
		mehendiPartySize: 0,
		isAttendingHaldi: "no",
		haldiPartySize: 0,
		isAttendingSangeet: "no",
		sangeetPartySize: 0,
		isAttendingMuhurtham: "no",
		muhurthamPartySize: 0,
		isAttendingReception: "no",
		receptionPartySize: 0,
		isAttendingShinzenshiki: "no",
		shinzenshikiPartySize: 0,
		isAttendingHiroen: "no",
		hiroenPartySize: 0,
		lastRSVPUpdateTime: "2024-05-26 10:00",
		partyMembers: "avani",
		allergies: "none"
	},
	{
		guest_id: "aswed206",
		name: "サーカー慎悟",
		email: "shingosarkar@gmail.com",
		password: "fionashome301",
		ReceptionOnly: false,
		SangeetReceptionOnly: false,
		SanMuhRec: false,
		AllEvents: false,
		AllUSJapan: false,
		JapanOnly: true,
		isAttendingMehendi: "no",
		mehendiPartySize: 0,
		isAttendingHaldi: "no",
		haldiPartySize: 0,
		isAttendingSangeet: "no",
		sangeetPartySize: 0,
		isAttendingMuhurtham: "no",
		muhurthamPartySize: 0,
		isAttendingReception: "no",
		receptionPartySize: 0,
		isAttendingShinzenshiki: "no",
		shinzenshikiPartySize: 0,
		isAttendingHiroen: "no",
		hiroenPartySize: 0,
		lastRSVPUpdateTime: "2024-05-26 10:00",
		partyMembers: "avani",
		allergies: "none"
	},
	{
		guest_id: "aswed207",
		name: "大谷萌",
		email: "daniel.star8@icloud.com",
		password: "fionashome301",
		ReceptionOnly: false,
		SangeetReceptionOnly: false,
		SanMuhRec: false,
		AllEvents: false,
		AllUSJapan: false,
		JapanOnly: true,
		isAttendingMehendi: "no",
		mehendiPartySize: 0,
		isAttendingHaldi: "no",
		haldiPartySize: 0,
		isAttendingSangeet: "no",
		sangeetPartySize: 0,
		isAttendingMuhurtham: "no",
		muhurthamPartySize: 0,
		isAttendingReception: "no",
		receptionPartySize: 0,
		isAttendingShinzenshiki: "no",
		shinzenshikiPartySize: 0,
		isAttendingHiroen: "no",
		hiroenPartySize: 0,
		lastRSVPUpdateTime: "2024-05-26 10:00",
		partyMembers: "avani",
		allergies: "none"
	},
	{
		guest_id: "aswed208",
		name: "吉村大暉",
		email: "hirokiy829@gmail.com",
		password: "fionashome301",
		ReceptionOnly: false,
		SangeetReceptionOnly: false,
		SanMuhRec: false,
		AllEvents: false,
		AllUSJapan: false,
		JapanOnly: true,
		isAttendingMehendi: "no",
		mehendiPartySize: 0,
		isAttendingHaldi: "no",
		haldiPartySize: 0,
		isAttendingSangeet: "no",
		sangeetPartySize: 0,
		isAttendingMuhurtham: "no",
		muhurthamPartySize: 0,
		isAttendingReception: "no",
		receptionPartySize: 0,
		isAttendingShinzenshiki: "no",
		shinzenshikiPartySize: 0,
		isAttendingHiroen: "no",
		hiroenPartySize: 0,
		lastRSVPUpdateTime: "2024-05-26 10:00",
		partyMembers: "avani",
		allergies: "none"
	},
	{
		guest_id: "aswed209",
		name: "山口大地",
		email: "bananasplit4649@gmail.com",
		password: "fionashome301",
		ReceptionOnly: false,
		SangeetReceptionOnly: false,
		SanMuhRec: false,
		AllEvents: false,
		AllUSJapan: false,
		JapanOnly: true,
		isAttendingMehendi: "no",
		mehendiPartySize: 0,
		isAttendingHaldi: "no",
		haldiPartySize: 0,
		isAttendingSangeet: "no",
		sangeetPartySize: 0,
		isAttendingMuhurtham: "no",
		muhurthamPartySize: 0,
		isAttendingReception: "no",
		receptionPartySize: 0,
		isAttendingShinzenshiki: "no",
		shinzenshikiPartySize: 0,
		isAttendingHiroen: "no",
		hiroenPartySize: 0,
		lastRSVPUpdateTime: "2024-05-26 10:00",
		partyMembers: "avani",
		allergies: "none"
	},
	{
		guest_id: "aswed210",
		name: "川上真生",
		email: "kawa222@icloud.com",
		password: "fionashome301",
		ReceptionOnly: false,
		SangeetReceptionOnly: false,
		SanMuhRec: false,
		AllEvents: false,
		AllUSJapan: false,
		JapanOnly: true,
		isAttendingMehendi: "no",
		mehendiPartySize: 0,
		isAttendingHaldi: "no",
		haldiPartySize: 0,
		isAttendingSangeet: "no",
		sangeetPartySize: 0,
		isAttendingMuhurtham: "no",
		muhurthamPartySize: 0,
		isAttendingReception: "no",
		receptionPartySize: 0,
		isAttendingShinzenshiki: "no",
		shinzenshikiPartySize: 0,
		isAttendingHiroen: "no",
		hiroenPartySize: 0,
		lastRSVPUpdateTime: "2024-05-26 10:00",
		partyMembers: "avani",
		allergies: "none"
	},
	{
		guest_id: "aswed211",
		name: "石川和樹",
		email: "kazuki0310stone@gmail.com",
		password: "fionashome301",
		ReceptionOnly: false,
		SangeetReceptionOnly: false,
		SanMuhRec: false,
		AllEvents: false,
		AllUSJapan: false,
		JapanOnly: true,
		isAttendingMehendi: "no",
		mehendiPartySize: 0,
		isAttendingHaldi: "no",
		haldiPartySize: 0,
		isAttendingSangeet: "no",
		sangeetPartySize: 0,
		isAttendingMuhurtham: "no",
		muhurthamPartySize: 0,
		isAttendingReception: "no",
		receptionPartySize: 0,
		isAttendingShinzenshiki: "no",
		shinzenshikiPartySize: 0,
		isAttendingHiroen: "no",
		hiroenPartySize: 0,
		lastRSVPUpdateTime: "2024-05-26 10:00",
		partyMembers: "avani",
		allergies: "none"
	},
	{
		guest_id: "aswed212",
		name: "酒井悠輔",
		email: "yuu1suke1@gmail.com",
		password: "fionashome301",
		ReceptionOnly: false,
		SangeetReceptionOnly: false,
		SanMuhRec: false,
		AllEvents: false,
		AllUSJapan: false,
		JapanOnly: true,
		isAttendingMehendi: "no",
		mehendiPartySize: 0,
		isAttendingHaldi: "no",
		haldiPartySize: 0,
		isAttendingSangeet: "no",
		sangeetPartySize: 0,
		isAttendingMuhurtham: "no",
		muhurthamPartySize: 0,
		isAttendingReception: "no",
		receptionPartySize: 0,
		isAttendingShinzenshiki: "no",
		shinzenshikiPartySize: 0,
		isAttendingHiroen: "no",
		hiroenPartySize: 0,
		lastRSVPUpdateTime: "2024-05-26 10:00",
		partyMembers: "avani",
		allergies: "none"
	},
	{
		guest_id: "aswed213",
		name: "伊藤たかし",
		email: "anakin7081@gmail.com",
		password: "fionashome301",
		ReceptionOnly: false,
		SangeetReceptionOnly: false,
		SanMuhRec: false,
		AllEvents: false,
		AllUSJapan: false,
		JapanOnly: true,
		isAttendingMehendi: "no",
		mehendiPartySize: 0,
		isAttendingHaldi: "no",
		haldiPartySize: 0,
		isAttendingSangeet: "no",
		sangeetPartySize: 0,
		isAttendingMuhurtham: "no",
		muhurthamPartySize: 0,
		isAttendingReception: "no",
		receptionPartySize: 0,
		isAttendingShinzenshiki: "no",
		shinzenshikiPartySize: 0,
		isAttendingHiroen: "no",
		hiroenPartySize: 0,
		lastRSVPUpdateTime: "2024-05-26 10:00",
		partyMembers: "avani",
		allergies: "none"
	},
	{
		guest_id: "aswed214",
		name: "鍋谷隼人",
		email: "nabe_baseball1111@yahoo.co.jp",
		password: "fionashome301",
		ReceptionOnly: false,
		SangeetReceptionOnly: false,
		SanMuhRec: false,
		AllEvents: false,
		AllUSJapan: false,
		JapanOnly: true,
		isAttendingMehendi: "no",
		mehendiPartySize: 0,
		isAttendingHaldi: "no",
		haldiPartySize: 0,
		isAttendingSangeet: "no",
		sangeetPartySize: 0,
		isAttendingMuhurtham: "no",
		muhurthamPartySize: 0,
		isAttendingReception: "no",
		receptionPartySize: 0,
		isAttendingShinzenshiki: "no",
		shinzenshikiPartySize: 0,
		isAttendingHiroen: "no",
		hiroenPartySize: 0,
		lastRSVPUpdateTime: "2024-05-26 10:00",
		partyMembers: "avani",
		allergies: "none"
	},
]

module.exports = {
	new_guest_1
};
