// This file contains placeholder data that you'll be replacing with real data in the Data Fetching chapter:
// https://nextjs.org/learn/dashboard-app/fetching-data
const guest_test = [
  {
    guest_id: 'guesttest1',
    name: 'Avani Pai',
    email: 'avanipai695@gmail.com',
	password: 'fionashome301',
	ReceptionOnly: false,
	SangeetReceptionOnly: false,
	SanMuhRec: false,
	AllEvents: false,
	AllUSJapan: true,
	isAttendingMehendi: "no",
	mehendiPartySize: 2,
	isAttendingHaldi: "no",
	haldiPartySize: 2,
	isAttendingSangeet: "no",
	sangeetPartySize: 2,
	isAttendingMuhurtham: "no",
	muhurthamPartySize: 2,
	isAttendingReception: "no",
	receptionPartySize: 2,
	isAttendingShinzenshiki: "no",
	shinzenshikiPartySize: 2,
	isAttendingHiroen: "no",
	hiroenPartySize: 2,
	lastRSVPUpdateTime: '2024-05-26 10:00',
	partyMembers: '',
	allergies: 'none',
  },
  {
    guest_id: 'guesttest4',
    name: 'Ganesh Pai',
    email: 'ganeshrpai@gmail.com',
	password: 'fionashome301',
	ReceptionOnly: false,
	SangeetReceptionOnly: false,
	SanMuhRec: false,
	AllEvents: true,
	AllUSJapan: false,
	isAttendingMehendi: "no",
	mehendiPartySize: 2,
	isAttendingHaldi: "no",
	haldiPartySize: 2,
	isAttendingSangeet: "no",
	sangeetPartySize: 2,
	isAttendingMuhurtham: "no",
	muhurthamPartySize: 2,
	isAttendingReception: "no",
	receptionPartySize: 2,
	isAttendingShinzenshiki: "no",
	shinzenshikiPartySize: 2,
	isAttendingHiroen: "no",
	hiroenPartySize: 2,
	lastRSVPUpdateTime: '2024-05-26 10:00',
	partyMembers: '',
	allergies: 'none',
  },
  {
    guest_id: 'guesttest5',
    name: 'Latha Pai',
    email: 'lpai265@gmail.com',
	password: 'fionashome301',
	ReceptionOnly: false,
	SangeetReceptionOnly: false,
	SanMuhRec: true,
	AllEvents: false,
	AllUSJapan: false,
	isAttendingMehendi: "no",
	mehendiPartySize: 2,
	isAttendingHaldi: "no",
	haldiPartySize: 2,
	isAttendingSangeet: "no",
	sangeetPartySize: 2,
	isAttendingMuhurtham: "no",
	muhurthamPartySize: 2,
	isAttendingReception: "no",
	receptionPartySize: 2,
	isAttendingShinzenshiki: "no",
	shinzenshikiPartySize: 2,
	isAttendingHiroen: "no",
	hiroenPartySize: 2,
	lastRSVPUpdateTime: '2024-05-26 10:00',
	partyMembers: '',
	allergies: 'none',
  },
  {
    guest_id: 'guesttest6',
    name: 'Oorvi Pai',
    email: 'oorvipai21@gmail.com',
	password: 'fionashome301',
	ReceptionOnly: false,
	SangeetReceptionOnly: true,
	SanMuhRec: false,
	AllEvents: false,
	AllUSJapan: false,
	isAttendingMehendi: "no",
	mehendiPartySize: 2,
	isAttendingHaldi: "no",
	haldiPartySize: 2,
	isAttendingSangeet: "no",
	sangeetPartySize: 2,
	isAttendingMuhurtham: "no",
	muhurthamPartySize: 2,
	isAttendingReception: "no",
	receptionPartySize: 2,
	isAttendingShinzenshiki: "no",
	shinzenshikiPartySize: 2,
	isAttendingHiroen: "no",
	hiroenPartySize: 2,
	lastRSVPUpdateTime: '2024-05-26 10:00',
	partyMembers: '',
	allergies: 'none',
  },
  {
    guest_id: 'guesttest7',
    name: 'Shusuke Sugimoto',
    email: 'fountainr409@gmail.com',
	password: 'fionashome301',
	ReceptionOnly: true,
	SangeetReceptionOnly: false,
	SanMuhRec: false,
	AllEvents: false,
	AllUSJapan: false,
	isAttendingMehendi: "no",
	mehendiPartySize: 2,
	isAttendingHaldi: "no",
	haldiPartySize: 2,
	isAttendingSangeet: "no",
	sangeetPartySize: 2,
	isAttendingMuhurtham: "no",
	muhurthamPartySize: 2,
	isAttendingReception: "no",
	receptionPartySize: 2,
	isAttendingShinzenshiki: "no",
	shinzenshikiPartySize: 2,
	isAttendingHiroen: "no",
	hiroenPartySize: 2,
	lastRSVPUpdateTime: '2024-05-26 10:00',
	partyMembers: '',
	allergies: 'none',
  },
];

module.exports = {
  guest_test
};
