// This file contains placeholder data that you'll be replacing with real data in the Data Fetching chapter:
// https://nextjs.org/learn/dashboard-app/fetching-data
const guest_test = [
  {
    guest_id: 'guesttest1',
    name: 'Avani Pai',
    email: 'avanipai695@gmail.com',
	password: 'fionashome301',
	isInvitedToHaldi: true,
	isInvitedToMehendi: true,
	isInvitedToSangeet: true,
	isInvitedToMuhurtham: true,
	isInvitedToReception: true,
	isInvitedToShinzenshiki: true,
	isInvitedToHiroen: true,
	allergies: 'dairy',
	isAttendingHaldi: "no",
	isAttendingMehendi: "no",
	isAttendingSangeet: "no",
	isAttendingMuhurtham: "no",
	isAttendingReception: "no",
	isAttendingShinzenshiki: "no",
	isAttendingHiroen: "no",
	lastRSVPUpdateTime: '2024-05-26 10:00',
	partySize: 2,
	partyMembers: 'Fiona',
  },
  {
    guest_id: 'guesttest2',
    name: 'Avani Sugimoto',
    email: 'animeloveravani@gmail.com',
	password: 'fionashome301',
	isInvitedToHaldi: true,
	isInvitedToMehendi: true,
	isInvitedToSangeet: true,
	isInvitedToMuhurtham: true,
	isInvitedToReception: true,
	isInvitedToShinzenshiki: false,
	isInvitedToHiroen: false,
	allergies: 'dairy',
	isAttendingHaldi: "no",
	isAttendingMehendi: "no",
	isAttendingSangeet: "no",
	isAttendingMuhurtham: "no",
	isAttendingReception: "no",
	isAttendingShinzenshiki: "no",
	isAttendingHiroen: "no",
	lastRSVPUpdateTime: '2024-05-26 10:00',
	partySize: 2,
	partyMembers: 'Fioneko',
  },
  {
    guest_id: 'guesttest3',
    name: 'Avani Copilot',
    email: 'avpai@microsoft.com',
	password: 'fionashome301',
	isInvitedToHaldi: false,
	isInvitedToMehendi: true,
	isInvitedToSangeet: true,
	isInvitedToMuhurtham: true,
	isInvitedToReception: true,
	isInvitedToShinzenshiki: false,
	isInvitedToHiroen: false,
	allergies: 'dairy',
	isAttendingHaldi: "no",
	isAttendingMehendi: "no",
	isAttendingSangeet: "no",
	isAttendingMuhurtham: "no",
	isAttendingReception: "no",
	isAttendingShinzenshiki: "no",
	isAttendingHiroen: "no",
	lastRSVPUpdateTime: '2024-05-26 10:00',
	partySize: 2,
	partyMembers: 'Fiona',
  },
  {
    guest_id: 'guesttest4',
    name: 'Ganesh Pai',
    email: 'ganeshrpai@gmail.com',
	password: 'fionashome301',
	isInvitedToHaldi: false,
	isInvitedToMehendi: false,
	isInvitedToSangeet: true,
	isInvitedToMuhurtham: true,
	isInvitedToReception: true,
	isInvitedToShinzenshiki: false,
	isInvitedToHiroen: false,
	allergies: 'dairy',
	isAttendingHaldi: "no",
	isAttendingMehendi: "no",
	isAttendingSangeet: "no",
	isAttendingMuhurtham: "no",
	isAttendingReception: "no",
	isAttendingShinzenshiki: "no",
	isAttendingHiroen: "no",
	lastRSVPUpdateTime: '2024-05-26 10:00',
	partySize: 2,
	partyMembers: 'Rustyfafa',
  },
  {
    guest_id: 'guesttest5',
    name: 'Latha Pai',
    email: 'lpai265@gmail.com',
	password: 'fionashome301',
	isInvitedToHaldi: false,
	isInvitedToMehendi: false,
	isInvitedToSangeet: false,
	isInvitedToMuhurtham: true,
	isInvitedToReception: true,
	isInvitedToShinzenshiki: false,
	isInvitedToHiroen: false,
	allergies: 'dairy',
	isAttendingHaldi: "no",
	isAttendingMehendi: "no",
	isAttendingSangeet: "no",
	isAttendingMuhurtham: "no",
	isAttendingReception: "no",
	isAttendingShinzenshiki: "no",
	isAttendingHiroen: "no",
	lastRSVPUpdateTime: '2024-05-26 10:00',
	partySize: 2,
	partyMembers: 'Rusty',
  },
  {
    guest_id: 'guesttest6',
    name: 'Oorvi Pai',
    email: 'oorvipai21@gmail.com',
	password: 'fionashome301',
	isInvitedToHaldi: false,
	isInvitedToMehendi: false,
	isInvitedToSangeet: false,
	isInvitedToMuhurtham: false,
	isInvitedToReception: true,
	isInvitedToShinzenshiki: false,
	isInvitedToHiroen: false,
	allergies: 'dairy',
	isAttendingHaldi: "no",
	isAttendingMehendi: "no",
	isAttendingSangeet: "no",
	isAttendingMuhurtham: "no",
	isAttendingReception: "no",
	isAttendingShinzenshiki: "no",
	isAttendingHiroen: "no",
	lastRSVPUpdateTime: '2024-05-26 10:00',
	partySize: 2,
	partyMembers: 'Asher',
  },
  {
    guest_id: 'guesttest7',
    name: 'Shusuke Sugimoto',
    email: 'fountainr409@gmail.com',
	password: 'fionashome301',
	isInvitedToHaldi: false,
	isInvitedToMehendi: false,
	isInvitedToSangeet: false,
	isInvitedToMuhurtham: false,
	isInvitedToReception: false,
	isInvitedToShinzenshiki: true,
	isInvitedToHiroen: true,
	allergies: 'dairy',
	isAttendingHaldi: "no",
	isAttendingMehendi: "no",
	isAttendingSangeet: "no",
	isAttendingMuhurtham: "no",
	isAttendingReception: "no",
	isAttendingShinzenshiki: "no",
	isAttendingHiroen: "no",
	lastRSVPUpdateTime: '2024-05-26 10:00',
	partySize: 2,
	partyMembers: 'Fiona',
  },
];

module.exports = {
  guest_test
};
